site_name: VPS de Info3
site_dir: /var/www/localhost/htdocs/2025/sitio
site_author: "Jurandy Soares & Info3{M,V}"

theme:
  name: readthedocs
  language: pt

plugins:
  - search
  - mermaid2
  - table-reader

nav:
  - index.md
  - diagramas.md
  - usuarios.md

